-- T-003 baseline: tables owned by the shared module (docs/architecture/domain-model.md).
-- IDs are UUID v7 generated by the application; the seed rows below use gen_random_uuid().

create table setting (
    id         uuid         primary key,
    key        varchar(100) not null,
    value      varchar(500) not null,
    updated_by uuid,
    created_at timestamptz  not null default now(),
    updated_at timestamptz  not null default now(),
    version    bigint       not null default 0,
    constraint setting_key_uq unique (key)
);

-- Defaults from docs/product/business-rules.md. club.timezone is configuration, not a setting.
insert into setting (id, key, value) values
    (gen_random_uuid(), 'slot.default-capacity', '10'),                    -- BR-03
    (gen_random_uuid(), 'slot.booking-horizon-days', '14'),                -- BR-05
    (gen_random_uuid(), 'slot.cutoff-minutes', '120'),                     -- BR-06
    (gen_random_uuid(), 'loan.period-days', '14'),                         -- BR-07
    (gen_random_uuid(), 'loan.max-renewals', '1'),                         -- BR-09
    (gen_random_uuid(), 'loan.possible-lost-after-days', '30'),            -- BR-11
    (gen_random_uuid(), 'limits.max-active-items', '5'),                   -- BR-12
    (gen_random_uuid(), 'limits.max-waitlist-entries', '5'),               -- BR-13
    (gen_random_uuid(), 'limits.max-children', '6'),                       -- BR-15
    (gen_random_uuid(), 'promotion.choose-slot-hours', '48'),              -- BR-19
    (gen_random_uuid(), 'noshow.flag-count', '3'),                         -- BR-21
    (gen_random_uuid(), 'noshow.flag-days', '60'),                         -- BR-21
    (gen_random_uuid(), 'reminder.pickup-hours-before', '24'),             -- BR-32
    (gen_random_uuid(), 'reminder.due-soon-days', '2'),                    -- BR-33
    (gen_random_uuid(), 'reminder.overdue-days', '1,4,8'),                 -- BR-34
    (gen_random_uuid(), 'reminder.awaiting-slot-hours-before-expiry', '24'), -- BR-35
    (gen_random_uuid(), 'retention.inactive-months', '24');                -- BR-37

-- FR-ADM-03. details holds IDs and codes only, never personal data.
create table audit_log (
    id               uuid         primary key,
    actor_account_id uuid,
    action           varchar(100) not null,
    entity_type      varchar(100) not null,
    entity_id        uuid,
    details          jsonb        not null default '{}'::jsonb,
    at               timestamptz  not null,
    created_at       timestamptz  not null default now(),
    updated_at       timestamptz  not null default now()
);

create index audit_log_at_idx on audit_log (at desc);
create index audit_log_entity_idx on audit_log (entity_type, entity_id);

-- ShedLock standard table (job locks, one runner at a time across instances).
create table shedlock (
    name       varchar(64)  primary key,
    lock_until timestamptz  not null,
    locked_at  timestamptz  not null,
    locked_by  varchar(255) not null
);
